// Generated by build script, do not edit!
// This file is generated for the sole purpose of being included in Windows resource (.rc) files.
// DO NOT INCLUDE THIS FILE IN C++ CODE. Use #include "Runtime/Utilities/UnityConfiguration.h" instead.
#define UNITY_VERSION_BLD 1436286
#define UNITY_VERSION_UNDER_HASH "6000.0.39f1_15ea7ed0b100"
#define UNITY_VERSION_PARENS_HASH "6000.0.39f1 (15ea7ed0b100)"
#define UNITY_VERSION_WIN "6000.0.39.1436286"
